### ISSUE TITLE
Hiding the combo counter

### ISSUE THREAD

**Issue by tuur29** [Caeden117/CountersPlus#11]
I don't see a way to hide /move the combo counter (and ring).
Would it be possible to add this as a setting?

**Comment by Caeden117** [comment]
I'll consider it. I've been thinking about letting you control the combo/multiplier panels anyways, so I might do it when the new Beat Saber update hits.

**Comment by Caeden117** [comment]
As of Counters+ 1.5.0 for Beat Saber 0.13 you can now disable the counter and multiplier while in game.
