### ISSUE TITLE
Mod restarts every time I open the game

### ISSUE THREAD

**Issue by OnlyAdqm** [Caeden117/CountersPlus#110]
**Describe the Bug**
Whenever I open my 1.18 beat saber, Counters+ seems to never have been installed. By default, it's not even enabled and all it's previous settings have vanished. I then set it up properly, play, close the game and the cycle repeats.

**Attach or Link Files**
[_latest.log](https://github.com/Caeden117/CountersPlus/files/7739959/_latest.log)

**Screenshots or Video**
If applicable, add screenshots or videos to help me out. Sometimes, words ain't enough!

**Additional context**
I've tried closing the game in multiple ways - closing it via the main menu, alt+f4, or even closing SteamVR - the result is always the same.

**Comment by Caeden117** [comment]
Hi,

Counters+ versions `2.2.3` and `2.2.4` are known to be buggy and should not be installed. In fact, I should probably take them off of Github when I get more time.

I recommend you install `2.2.2` from GitHub. The next version is almost ready for Beat Saber 1.19, I am waiting for mods to be uploaded to ModAssistant.
