### ISSUE TITLE
Counters+ is broken on 1.18.3

### ISSUE THREAD

**Issue by Velheor9001** [Caeden117/CountersPlus#111]
**Description:** 
The plugin does not work on the latest moddable version. The UI does not show up when entering its settings. Tested with only Counters+ dependencies installed. 

**Logs:** 
[_latest.log](https://github.com/Caeden117/CountersPlus/files/7749581/_latest.log)
[CountersPlus.txt](https://github.com/Caeden117/CountersPlus/files/7749585/CountersPlus.txt)

> [CRITICAL @ 20:38:56 | UnityEngine] KeyNotFoundException: The given key was not present in the dictionary.
[CRITICAL @ 20:38:56 | UnityEngine] System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
[CRITICAL @ 20:38:56 | UnityEngine] CountersPlus.Utils.CanvasUtility.CreateTextFromSettings (CountersPlus.ConfigModels.ConfigModel settings, System.Nullable`1[T] offset) (at <4552991e560344699ec3dc0e861d2962>:0)
[CRITICAL @ 20:38:56 | UnityEngine] CountersPlus.UI.MockCounter.UpdateMockCounter (CountersPlus.ConfigModels.ConfigModel settings) (at <4552991e560344699ec3dc0e861d2962>:0)
[CRITICAL @ 20:38:56 | UnityEngine] CountersPlus.UI.FlowCoordinators.CountersPlusSettingsFlowCoordinator.RefreshAllMockCounters () (at <4552991e560344699ec3dc0e861d2962>:0)
[CRITICAL @ 20:38:56 | UnityEngine] CountersPlus.UI.FlowCoordinators.CountersPlusSettingsFlowCoordinator.DidActivate (System.Boolean firstActivation, System.Boolean addedToHierarchy, System.Boolean screenSystemEnabling) (at <4552991e560344699ec3dc0e861d2962>:0)
[CRITICAL @ 20:38:56 | UnityEngine] HMUI.FlowCoordinator.Activate (System.Boolean firstActivation, System.Boolean addedToHierarchy, System.Boolean screenSystemEnabling) (at <4ed6ccd55f634459bd4b39b724b413c6>:0)
[CRITICAL @ 20:38:56 | UnityEngine] HMUI.FlowCoordinator.PresentFlowCoordinator (HMUI.FlowCoordinator flowCoordinator, System.Action finishedCallback, HMUI.ViewController+AnimationDirection animationDirection, System.Boolean immediately, System.Boolean replaceTopViewController) (at <4ed6ccd55f634459bd4b39b724b413c6>:0)
[CRITICAL @ 20:38:56 | UnityEngine] BeatSaberMarkupLanguage.BeatSaberUI.PresentFlowCoordinator (HMUI.FlowCoordinator current, HMUI.FlowCoordinator flowCoordinator, System.Action finishedCallback, HMUI.ViewController+AnimationDirection animationDirection, System.Boolean immediately, System.Boolean replaceTopViewController) (at <5fc3fa84aebb4325810c2779e62189cf>:0)
[CRITICAL @ 20:38:56 | UnityEngine] CountersPlus.UI.MenuButtonManager.<SummonFlowCoordinator>b__4_0 () (at <4552991e560344699ec3dc0e861d2962>:0)
[CRITICAL @ 20:38:56 | UnityEngine] CountersPlus.UI.FlowCoordinators.CountersPlusSettingsFlowCoordinator+<>c__DisplayClass21_0.<DoSceneTransition>b__0 (Zenject.DiContainer _) (at <4552991e560344699ec3dc0e861d2962>:0)
[CRITICAL @ 20:38:56 | UnityEngine] GameScenesManager+<>c__DisplayClass30_0.<PushScenes>b__1 (Zenject.DiContainer container) (at <09a448c281024307b38abd59cf7acfa0>:0)
[CRITICAL @ 20:38:56 | UnityEngine] GameScenesManager+<ScenesTransitionCoroutine>d__36.MoveNext () (at <09a448c281024307b38abd59cf7acfa0>:0)
[CRITICAL @ 20:38:56 | UnityEngine] UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <451019b49f1347529b43a32c5de769af>:0)

![image](https://user-images.githubusercontent.com/46257780/146872100-e57c343a-99f5-4e84-897a-b8b1a31e675e.png)

**Comment by Caeden117** [comment]
Counters+ `2.2.3` and `2.2.4` are known to be buggy and problematic. I have removed them from GitHub releases. Please downgrade to `2.2.2` while we wait for mods to become available for Beat Saber 1.19.
