### ISSUE TITLE
What is the measurement unit for the Average Speed qounter (kilometer per hour, miles per hour, etc)? 

### ISSUE THREAD

**Issue by pedro-german** [Caeden117/CountersPlus#117]
A question just out of curiosity. Also I like to know how fast I can get until I get rapidly exhausted

**Comment by Caeden117** [comment]
Answered in the [wiki](https://github.com/Caeden117/CountersPlus/wiki/Speed#speed-vs-spinometer) (Meters per second, measured at the tip of your sabers)
