### ISSUE TITLE
Disabled Counters+ breaks Multi

### ISSUE THREAD

**Issue by whymoo** [Caeden117/CountersPlus#126]
**Describe the Bug**
If Coutners+ is installed but disabled for just one person in a multiplayer lobby, the map won't load for anyone

**Log**
Full: https://pastebin.com/t0rNX2fP
Where it breaks:
`
[CRITICAL @ 14:11:36 | UnityEngine] ZenjectException: Unable to resolve 'CanvasUtility' while building object with type 'CanvasIntroFadeController'. Object graph:
[CRITICAL @ 14:11:36 | UnityEngine] DefaultGameObjectKernel
[CRITICAL @ 14:11:36 | UnityEngine] TickableManager
[CRITICAL @ 14:11:36 | UnityEngine] CanvasIntroFadeController
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectMembersTopDown (System.Object injectable, System.Type injectableType, Zenject.InjectTypeInfo typeInfo, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier, System.Boolean isDryRun) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicitInternal (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicit (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.TransientProvider+<>c__DisplayClass11_0.<GetAllInstancesWithInjectSplit>b__0 () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] args, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.GetDecoratedInstances (Zenject.IProvider provider, Zenject.InjectContext context, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.SafeGetInstances (Zenject.DiContainer+ProviderInfo providerInfo, Zenject.InjectContext context, System.Collections.Generic.List`1[T] instances) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.ResolveAll (Zenject.InjectContext context, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.ResolveAll (Zenject.InjectContext context) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectMembersTopDown (System.Object injectable, System.Type injectableType, Zenject.InjectTypeInfo typeInfo, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier, System.Boolean isDryRun) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicitInternal (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicit (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.TransientProvider+<>c__DisplayClass11_0.<GetAllInstancesWithInjectSplit>b__0 () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] args, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.GetDecoratedInstances (Zenject.IProvider provider, Zenject.InjectContext context, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.SafeGetInstances (Zenject.DiContainer+ProviderInfo providerInfo, Zenject.InjectContext context, System.Collections.Generic.List`1[T] instances) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.Resolve (Zenject.InjectContext context) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectMembersTopDown (System.Object injectable, System.Type injectableType, Zenject.InjectTypeInfo typeInfo, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier, System.Boolean isDryRun) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectMembersTopDown (System.Object injectable, System.Type injectableType, Zenject.InjectTypeInfo typeInfo, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier, System.Boolean isDryRun) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicitInternal (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicit (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.AddToGameObjectComponentProviderBase+<>c__DisplayClass17_0.<GetAllInstancesWithInjectSplit>b__0 () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] args, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.GetDecoratedInstances (Zenject.IProvider provider, Zenject.InjectContext context, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.SafeGetInstances (Zenject.DiContainer+ProviderInfo providerInfo, Zenject.InjectContext context, System.Collections.Generic.List`1[T] instances) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.ResolveDependencyRoots () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.ResolveRoots () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.GameObjectContext.RunInternal () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.RunnableContext.Run () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.RunnableContext.Initialize () (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.GameObjectContext.Construct (Zenject.DiContainer parentContainer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.GameObjectContext.__zenInjectMethod0 (System.Object P_0, System.Object[] P_1) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.CallInjectMethodsTopDown (System.Object injectable, System.Type injectableType, Zenject.InjectTypeInfo typeInfo, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier, System.Boolean isDryRun) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicitInternal (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicit (System.Object injectable, System.Type injectableType, System.Collections.Generic.List`1[T] extraArgs, Zenject.InjectContext context, System.Object concreteIdentifier) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectExplicit (System.Object injectable, System.Collections.Generic.List`1[T] extraArgs) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.Inject (System.Object injectable, System.Collections.Generic.IEnumerable`1[T] extraArgs) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.Inject (System.Object injectable) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InjectGameObject (UnityEngine.GameObject gameObject) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.DiContainer.InstantiatePrefab (UnityEngine.Object prefab, Zenject.GameObjectCreationParameters gameObjectBindInfo) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.SubContainerCreatorByNewPrefabWithParams.CreateSubContainer (System.Collections.Generic.List`1[T] args, Zenject.InjectContext parentContext) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.SubContainerDependencyProvider.GetAllInstancesWithInjectSplit (Zenject.InjectContext context, System.Collections.Generic.List`1[T] args, System.Action& injectAction, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetAllInstances (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] args, System.Collections.Generic.List`1[T] buffer) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.IProviderExtensions.GetInstance (Zenject.IProvider creator, Zenject.InjectContext context, System.Collections.Generic.List`1[T] args) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.PlaceholderFactoryBase`1[TValue].CreateInternal (System.Collections.Generic.List`1[T] extraArgs) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Rethrow as ZenjectException: Error during construction of type 'MultiplayerLocalActivePlayerFacade' via MultiplayerLocalActivePlayerFacade.Factory.Create method!
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.PlaceholderFactoryBase`1[TValue].CreateInternal (System.Collections.Generic.List`1[T] extraArgs) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] Zenject.PlaceholderFactory`2[TParam1,TValue].Create (TParam1 param) (at <ffafc91a7f454e738b71b6be53f0c887>:0)
[CRITICAL @ 14:11:36 | UnityEngine] MultiplayerPlayersManager.SpawnPlayers (MultiplayerPlayerStartState localPlayerStartState, System.Collections.Generic.IReadOnlyList`1[T] allActiveAtGameStartPlayers) (at <72bbc78157f343f28eb32d37b9e6fc26>:0)
[CRITICAL @ 14:11:36 | UnityEngine] MultiplayerController+<PerformSongStartSync>d__37.MoveNext () (at <72bbc78157f343f28eb32d37b9e6fc26>:0)
[CRITICAL @ 14:11:36 | UnityEngine] UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <451019b49f1347529b43a32c5de769af>:0)
`

**Comment by Caeden117** [comment]
This has been resolved in a currently unreleased version of Counters+. I will close this issue when Counters+ 2.3.1 is released.

**Comment by Caeden117** [comment]
Fixed in [Counters+ 2.3.1](https://github.com/Caeden117/CountersPlus/releases/tag/2.3.1)
