### ISSUE TITLE
CountersPlus Not Loading.

### ISSUE THREAD

**Issue by DeagleVR** [Caeden117/CountersPlus#131]
It wont load for me in 1.27.0

**Comment by DeagleVR** [comment]
when in menu i click a button called counters plus and when i clicked it it will not load

**Comment by PeterC43** [comment]
same thing for me but in 1.25

**Comment by DeagleVR** [comment]
Does It Work In 1.25.0 or 1.26.0 ?

**Comment by Caeden117** [comment]
i forgor 💀
