### ISSUE TITLE
Bombs and misses causing percentage and letter grade to drop

### ISSUE THREAD

**Issue by SarpestRazor** [Caeden117/CountersPlus#14]
When missing a note or a bomb occurs the percentage drop to 0% and the letter grade becomes "E". When hitting a note it returns to normal once more.

I'd assume that it's taking bombs and missed notes into account for scoring (as it should). But it is over weighing them
[C+ issue.zip](https://github.com/Caeden117/CountersPlus/files/3101777/C%2B.issue.zip)

**Comment by Caeden117** [comment]
The problem here was the additional call to the `UpdateScore` function in OnNoteMissed. Removing this call solves the issue, *however* the score will no longer update when a note is missed (I don't think it would matter that much anyways)
