### ISSUE TITLE
The counters are not showing up

### ISSUE THREAD

**Issue by fruitbat99** [Caeden117/CountersPlus#16]
after a song or two the counters dissapeared after i moved the miss counter to not interfere with the hud

**Comment by Caeden117** [comment]
Hi, this seems to be a problem I've yet to encounter on my own.

If you haven't upgraded to the new Counters+ 1.5.6 update, please do so via your Mod Manager of choice (Or manually via [BeatMods.](https://beatmods.com)), and check back with whether or not the issue persists in 1.5.6.

However, if you've already updated, here's some things I would like from you:

**Config (CountersPlus.ini)**
Located in the `UserData` folder of your Beat Saber directory, it would help me test your setup, as well as figure any potential issues from there.

**Recent Log (2019.05.03.something.log.gz)**
Located in the `Logs/Counters+` folder, this contains all the console output generated by Counters+, even if its an error that needs my attention.

Thanks!

**Comment by fruitbat99** [comment]
Hopefully this is what you need. I’ve also added the _latest.log.gz just in case and I am on 1.5.6 of counters+ using beat saber mod manager. The problem specifically started when I moved the misses counter because it was interfering with the score numbers on the new UI and later I moved it back to the default settings although I might have missed something.

Sent from Mail for Windows 10

**Comment by SarpestRazor** [comment]
So I'm having the exact same issue, but it happened out of the blue. I loaded up BS after updating mods and Counters+ broke, thought nothing of it. Recently installed CT so thought removing that would work, clearly it didn't. I even clean installed before I realized this was a documented issue.

Here's the log file after my clean install \/ \/
[2019.05.03.19.46.log.gz](https://github.com/Caeden117/CountersPlus/files/3144057/2019.05.03.19.46.log.gz)

**Comment by Caeden117** [comment]
The log file isn't giving me anything (Damnit, DaNike). If you ever get a chance to play Beat Saber, do you mind starting with `--verbose` as a launch argument (via Steam or Shortcut) and take a screenshot of that window when Counters+ breaks? (Should be highlighted in purple)

**Comment by SarpestRazor** [comment]
Went into a song, You can see exactly when I searched and played it. The error occurs after the song ends, weirdly.
![last](https://user-images.githubusercontent.com/47847357/57174810-0b3a9000-6de0-11e9-9d50-f3d9e3555077.PNG)

This was also in the log after I entered the "Failed" screen where I can restart or continue
![laster](https://user-images.githubusercontent.com/47847357/57174845-9e73c580-6de0-11e9-879e-9b963df4155e.PNG)

**Comment by Caeden117** [comment]
~~Ah shit, a null reference exception~~

It's getting really, *really* late so I'm going to head off for the night, I should fix it by the morning (hopefully).

In the time being, try regenerating the config file (simply moving the current one out of UserData would work) and see if that fixes stuff (probably not but worth a shot)

**Comment by SarpestRazor** [comment]
Yeah, nothing moves it from what I know, and as I said I clean installed and wiped everything and still having this issue. But good luck trying to fix this o/

**Comment by Caeden117** [comment]
I'm still going to need more than this.

How about you upload the last dated log in the base `Logs` folder, instead of the specific `Counters+` one? The logs in the base `Logs` folder should have everything from every mod, so I can go through and see if there's any exceptions happening

**Comment by fruitbat99** [comment]
[2019.05.03.16.17.log.gz](https://github.com/Caeden117/CountersPlus/files/3144637/2019.05.03.16.17.log.gz)
[_latest.log.gz](https://github.com/Caeden117/CountersPlus/files/3144638/_latest.log.gz)
[2019.05.02.18.03.log.gz] (https://github.com/Caeden117/CountersPlus/files/3144644/2019.05.02.18.03.log.gz) one from an earlier date so you can check from that i belive this one still had counters+ working

**Comment by Caeden117** [comment]
It looks like the issue might be from when Counters+ is attempting to hide the Combo and Multiplier
counters.

[Try this build out, and see if it solves anything.](https://github.com/Caeden117/CountersPlus/files/3144657/CountersPlus.zip)

**Comment by fruitbat99** [comment]
That Fixed it! Thanks!

**Comment by Caeden117** [comment]
Alright, I'll go ahead and post a Hotfix build for this, then.
