### ISSUE TITLE
Counters+ 1.5.6 (Hotfix 1) counters not showing

### ISSUE THREAD

**Issue by isaacay** [Caeden117/CountersPlus#17]
i have tried clean installing beatsaber then using the mod manager instaling the default mods and counters+ but even on default settings the counters arent showing in mods it shows and even shows its up to date i have even tried manually installing the latest version
counters+ log
[2019.05.15.18.22.log.gz](https://github.com/Caeden117/CountersPlus/files/3184904/2019.05.15.18.22.log.gz)
beatsaber log
[2019.05.15.18.22.log.gz](https://github.com/Caeden117/CountersPlus/files/3184903/2019.05.15.18.22.log.gz)

**Comment by Caeden117** [comment]
Hi,

Please check and make sure you have Beat Saber Utils installed, and ensure that it is placed in the Plugins folder. Also make sure that you have INI Parser installed, as that is required by Beat Saber Utils to function. You can find both of these in your mod manager of choice.

**Comment by isaacay** [comment]
![image](https://user-images.githubusercontent.com/15398757/57818020-6bfe8c80-773f-11e9-813b-578aae913311.png)
they are required i couldnt deselect them if i wanted to

**Comment by Caeden117** [comment]
```
[DEBUG @ 18:05:45 | IPA/LibraryLoader] Resolving library BS_Utils, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null
[DEBUG @ 18:05:45 | IPA/LibraryLoader] Looking for file BS_Utils.1.3.1.0.dll
[CRITICAL @ 18:05:45 | IPA/LibraryLoader] No library BS_Utils, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null found
[DEBUG @ 18:05:45 | IPA/LibraryLoader] Resolving library INIFileParser, Version=2.5.2.0, Culture=neutral, PublicKeyToken=79af7b307b65cf3c
[DEBUG @ 18:05:45 | IPA/LibraryLoader] Looking for file INIFileParser.2.5.2.0.dll
[CRITICAL @ 18:05:45 | IPA/LibraryLoader] No library INIFileParser, Version=2.5.2.0, Culture=neutral, PublicKeyToken=79af7b307b65cf3c found
[DEBUG @ 18:05:45 | IPA/LibraryLoader] Resolving library INIFileParser, Version=2.5.2.0, Culture=neutral, PublicKeyToken=79af7b307b65cf3c
[DEBUG @ 18:05:45 | IPA/LibraryLoader] Looking for file INIFileParser.2.5.2.0.dll
[CRITICAL @ 18:05:45 | IPA/LibraryLoader] No library INIFileParser, Version=2.5.2.0, Culture=neutral, PublicKeyToken=79af7b307b65cf3c found
```

According to your Beat Saber log, you do not have them installed (Or BSIPA isn't able to load them). Double check your plugins folder, just to be safe. If not, download them manually using the [BeatMods](https://beatmods.com/) website. Beat Saber Utils goes in the `Beat Saber/Plugins` folder, and INI Parser goes in `Beat Saber/Libs` folder.

**Comment by isaacay** [comment]
they where there but i downloaded them manually and replaced them and it still isnt loading

**Comment by Caeden117** [comment]
is SongLoader also working just fine? According to the log, SongLoader is also having issues loading from Beat Saber Utils.

**Comment by isaacay** [comment]
you maen custom songs right? im a noob i dont know what song loader does exactly

**Comment by Caeden117** [comment]
yea, custom songs

**Comment by isaacay** [comment]
ya its working i was able to load a custom map

**Comment by Caeden117** [comment]
Mind sending me a screenshot of your `Beat Saber/Plugins` folder?

**Comment by isaacay** [comment]
![image](https://user-images.githubusercontent.com/15398757/57818550-97827680-7741-11e9-9593-781e57c60629.png)
sure

**Comment by Caeden117** [comment]
[Try this build.....?](https://github.com/Caeden117/CountersPlus/files/3184964/CountersPlus.zip)

**Comment by isaacay** [comment]
still dont see counters in songs i can go into the counts+ settings but they dont show in songs

**Comment by Caeden117** [comment]
Check settings. Under `Main Settings` is the plugin enabled? Are some of the counters also enabled? If so, and they still aren't spawning, upload me your latest Beat Saber log file again (not Counters+ log file)

**Comment by isaacay** [comment]
strangly enough they where working at one point and without updating anything they stopped working i think i forgot to mention that then i updated to 1.5.6 hotpatch from 1.5.5

**Comment by isaacay** [comment]
by main settings do you mean countersplus.ini?

**Comment by Caeden117** [comment]
sure, but you could also go into the Counters+ settings menu and click on the `Main Settings` section (Might have to click on another thing then click on it)

**Comment by isaacay** [comment]
yes its enabled and there are ui elements enabled 
![image](https://user-images.githubusercontent.com/15398757/57818970-82a6e280-7743-11e9-9983-2e13e3c07294.png)
also heres it in a song
![image](https://user-images.githubusercontent.com/15398757/57818997-9b16fd00-7743-11e9-9d73-3b2902aa4733.png)

**Comment by Caeden117** [comment]
Ah.

It appears that you have `No HUD` enabled. Go into `Player Settings` when selecting a song, and see if you have that enabled.

**Comment by isaacay** [comment]
how did that get enabled now i feel stupid that i didnt check that...

**Comment by isaacay** [comment]
sorry for wasteing ur time

**Comment by Caeden117** [comment]
Nah, you're good. I should probably add an indicator that you have No HUD enabled.

I'll be sure to do that for the next update of Counters+.
