### ISSUE TITLE
[1.2.0] Settings are not saved

### ISSUE THREAD

**Issue by xhuytox** [Caeden117/CountersPlus#2]
How to reproduce:

- Open BeatSaber
- Change a setting inside the Counter menus (i.e. Notes enabled)
- Start a song (verify that Notes are visible)
- Exit the song
- Try to change the same setting (i.e. Notes disabled)
- Start a song (verify that Notes are STILL visible)

The settings are only saved the first time before playing a song. After a song has been played, no more settings are saved until you exit out of the game and reopen it.

**Comment by Caeden117** [comment]
Should now be fixed. Try using this build and see if that fixes it.
[CountersPlus.zip](https://github.com/Caeden117/CountersPlus/files/2753380/CountersPlus.zip)

**Comment by Caeden117** [comment]
With this final commit, I am pleased to say that this bug has been fixed *for good* in 1.3.0.

https://www.modsaber.org/mod/countersplus/1.3.0

I had to redo Config to fix it, but it's done.

**Comment by xhuytox** [comment]
Just tested. The settings are now saved correctly whenever. Thank you for all your work!

One possible bug. I noticed you fixed it so now the custom Score Counter shows both the score and the rank. That's awesome. While testing this, I noticed that the Override Base Counter setting inside the Score Counter tab is now the inverse of how it use to be. Now, when this is true, it shows the base game's score counter, and when it's false, it shows the custom counter. This seems like the opposite of what I thought this setting would do.

**Comment by xhuytox** [comment]
I think you should either change the label of the setting to "Use Base Game Counter" here:
https://github.com/Caeden117/CountersPlus/blob/c6ea4e1302139a9815f14b0c7fc4e3490bfde645/Counters%2B/CountersSettingsUI.cs#L79

or return the inverse of "UseOld" here:
https://github.com/Caeden117/CountersPlus/blob/c6ea4e1302139a9815f14b0c7fc4e3490bfde645/Counters%2B/CountersSettingsUI.cs#L80
