### ISSUE TITLE
Hiding Multiplier option doesn't work

### ISSUE THREAD

**Issue by tuur29** [Caeden117/CountersPlus#20]
The multiplier counter is still visible after turning the option to hide it on. I've reinstalled the mod and removed my config file, but it still doesn't work. I've manually checked the config file and it says `HideMultiplier = True` as expected ([my config file]([CountersPlus.zip](https://github.com/Caeden117/CountersPlus/files/3269424/CountersPlus.zip))).

My [latest log](https://github.com/Caeden117/CountersPlus/files/3269430/2019.06.09.12.17.log.zip) shows a warning on line 375: `Can't remove the Multiplier counter!`

**Comment by Caeden117** [comment]
Hmmm, I'm pretty sure Beat Saber just renamed some stuff around and broke that. I'll look into it when the new Beat Saber update drops tomorrow and include the fix in Counters+ 1.5.8.

**Comment by Caeden117** [comment]
Seems like I was just executing that code before I should be.

This issue has been fixed in Counters+ 1.5.8.

**Comment by tuur29** [comment]
Thanks!

**Comment by Aloki** [comment]
Option doesn't work again. Same message (_Can't remove the Multiplier counter!_) in log file.
Beat Saber 1.6.2, Counters+ 1.8.1.
