### ISSUE TITLE
Time Remaining under the Multiplier from Advanced HUD disappears when I enable CountersPlus

### ISSUE THREAD

**Issue by skippy186** [Caeden117/CountersPlus#25]
**Describe the Bug**
When I enable CountersPlus, the Time Left display disappears. It's not being overlaid by any of the new counters, it's just not there. 

**Attach or Link Files**

A helpful start will be to attach your current Counters+ Config (Located in `Beat Saber/UserData/CountersPlus.ini`) to this report. The file wasn't supported so here's the txt.

[Main]
Enabled = False
AdvancedCounterInfo = True
HideCombo = False
HideMultiplier = False
ComboOffset = 0.2
MultiplierOffset = 0.4

[Fail]
ShowRestartsInstead = False
Enabled = True
Position = BelowMultiplier
Index = 1

[Spinometer]
Mode = Average
Enabled = False
Position = AboveCombo
Index = 1

[Missed]
CustomMissTextIntegration = True
Enabled = False
Position = BelowMultiplier
Index = 0

[Notes]
ShowPercentage = True
DecimalPrecision = 0
Enabled = False
Position = BelowCombo
Index = 2

[Score]
Mode = Average
DecimalPrecision = 0
DisplayRank = False
Enabled = False
Position = AboveCombo
Index = 0

[Personal Best]
DecimalPrecision = 0
TextSize = 2
UnderScore = True
HideFirstScore = False
Enabled = True
Position = AboveMultiplier
Index = 0

[Progress]
Mode = Average
ProgressTimeLeft = False
IncludeRing = False
Enabled = True
Position = AboveHighway
Index = 0

[Speed]
DecimalPrecision = 0
Mode = Average
Enabled = False
Position = AboveHighway
Index = 0

[Cut]
Enabled = True
Position = BelowEnergy
Index = 0

[Notes Left]
LabelAboveCount = False
Enabled = True
Position = BelowCombo
Index = 1

If you wish to be even more helpful, try taking a screenshot of the Beat Saber Console when you reproduce the issue (`--verbose` in the start arguments. You can use Google to figure out how to take a screenshot.)

If you want to be my best friend, attach the latest log with a date and time name (**Not** `latest.log.gz`), located in `Beat Saber/Logs/Counters+`. Like this?
[2019.08.16.19.10.01.log.gz](https://github.com/Caeden117/CountersPlus/files/3511482/2019.08.16.19.10.01.log.gz)

**Probable Culprit**
Honestly, I'm most generally an idiot, so it's probably something that I'm (not) doing.

**Screenshots or Video**
I tried to, but it said the zip file was too big

**Additional context**

**Comment by Caeden117** [comment]
Progress mode is set to `Average`, which is invalid. Go into settings, and change it's mode to something else. If you can't, manually edit `CountersPlus.ini` and change `Average` to `Original`.

This seems to be a recurring issue, and I need to figure out what causes it.

**Comment by skippy186** [comment]
Wow, that was a super fast reply and fix! 
Yep, that did it. I ended up using Base Game over Original and I changed all of them in the .ini file. 

Thank you so much!
