### ISSUE TITLE
[Suggestion] README

### ISSUE THREAD

**Issue by xhuytox** [Caeden117/CountersPlus#3]
Please put a note inside the README that mentions that:

- For the Score Counter, if the Advanced HUD is not enabled, if the "Override" is enabled, it will show just the score (no rank). Else, if the "Override" is disabled, it will show just the rank (no score). 
- For the Progress Counter, if the Advanced HUD is not enabled and the "Base" type is chosen, no counter will show up.

**Comment by Caeden117** [comment]
README has been given a few updates. If you want anything else modified or added, DM me on discord: *Caeden117#0117*
