### ISSUE TITLE
score counter not working

### ISSUE THREAD

**Issue by Sneakometer** [Caeden117/CountersPlus#33]
**Describe the Bug**
The rank and percentage isn't updating. It's locked at 100% SS.

**Screenshot**
![Screenshot](https://user-images.githubusercontent.com/50603525/69196664-6723f680-0b2f-11ea-9b36-858370ab8eb2.PNG)

**Some attachments**
CountersPlus.ini and log:
[2019.11.19.23.50.40.log](https://github.com/Caeden117/CountersPlus/files/3866597/2019.11.19.23.50.40.log)
[CountersPlus.ini.txt](https://github.com/Caeden117/CountersPlus/files/3866599/CountersPlus.ini.txt)

**Other mods**
I used Modassistant to install CountersPlus besides these other mods:
- ScoreSaber, Songcore, SongDataCore
- CameraPlus
- CustomAvatar
- Mapping Extension
- LevelPackPanelMover
- SongBrowser
- TheTrashMan
- All the dependencies needed

Thanks.

**Comment by Caeden117** [comment]
Hi,

Seems like a bit more information is needed. Can you grab and upload `2019.11.19.23.50.40.log` from the general Logs folder rather than the Counters+ specific folder? It's just a directory up from where the Counters+ log was.

**Comment by Sneakometer** [comment]
Ok there is a NullReferenceException thrown by CountersPlus in ScoreCounter.CreateText ().
[general_2019.11.19.23.50.21.log](https://github.com/Caeden117/CountersPlus/files/3870264/general_2019.11.19.23.50.21.log)

**Comment by Caeden117** [comment]
Ah, I think I know what's up. I'll get to it as soon as I can.

**Comment by Caeden117** [comment]
Fixed in commit 644bdcca0040fa71c58edaa1cb800008b6401c97. This fix will appear in the next update to Counters+.
