### ISSUE TITLE
Unclear what this is for

### ISSUE THREAD

**Issue by StefanJanssen95** [Caeden117/CountersPlus#34]
It's neither a suggestion nor bug related to code so none of the templates really work.

This repo was listed in the "discoveries" and I was quite confused what this was a mod for. It was listing all kind of counters. I was skimming the page and did see something about notes and arms swinging so I assumed beatsaber.

I've not found any reference to beatsaber so for people randomly coming onto the repo it's quite unclear.

**Comment by Caeden117** [comment]
~~Wow, people actually use Discovery?~~

Uhh... yea, I never expected someone to randomly stumble across this from Discovery, nor did I expect GitHub to throw this on someone's Discovery queue.

The intended way to get to this GitHub repository was from the [Beat Saber mod repository](https://beatmods.com), a button in the mod itself, or perhaps by word of mouth and searching `counters+ beat saber mod` on Google or something.

Either way, this happened, and it looks like I have a README upgrade to do when I get back to this project.
