### ISSUE TITLE
Broken on 1.6.2

### ISSUE THREAD

**Issue by DanDon** [Caeden117/CountersPlus#38]
Using even the latest version you have here (1.8.0.-beta 1 currently) the mod is broken in Beat Saber v1.6.2.

The mod shows the counters when in game as it normally does but the menu to change or select or do anything with the mod is just blank. 

You can enter the Counters+ menu thought the mod settings menu and you are presented with the 3 options at the bottom and the description page to the left but no clickable or even visible mod settings under each of the three options.

**Comment by Caeden117** [comment]
![image](https://user-images.githubusercontent.com/30004286/72362145-7c3c8200-36a7-11ea-98c2-18cf962a4b41.png)

That release was for versions 1.6.0-1.6.1. Counters+ for 1.6.2 is currently undergoing a minor internal rewrite, so please wait patiently.
