### ISSUE TITLE
Hide multiplier option doesn't work again

### ISSUE THREAD

**Issue by Aloki** [Caeden117/CountersPlus#39]
Issue #20 is present again.
Beat Saber 1.6.2, Counters+ 1.8.1

**Comment by Caeden117** [comment]
![image](https://user-images.githubusercontent.com/30004286/73036187-9bea4d80-3dff-11ea-9277-5ccd44dc13ca.png)

Replace `Counters+ 1.5.8` with `Counters+ 1.8.2` and me finally getting off my lazy ass and making that little bit of code not break every time the game updates
