### ISSUE TITLE
Hide Multiplier

### ISSUE THREAD

**Issue by kats1123** [Caeden117/CountersPlus#42]
The disable multiplier feature doesn't work. Essentially when the box is ticked, the multiplier is still visible in game. When attempted with advance HUD off, same issue. Works fine with combo tho. 

Config: 
[Fail]
ShowRestartsInstead = False
Enabled = False
Position = AboveCombo
Distance = 0

[Missed]
CustomMissTextIntegration = False
Enabled = True
Position = AboveCombo
Distance = 0

[Notes]
ShowPercentage = False
DecimalPrecision = 2
Enabled = True
Position = BelowEnergy
Distance = 0

[Progress]
Mode = Original
ProgressTimeLeft = True
IncludeRing = True
Enabled = True
Position = BelowMultiplier
Distance = -1

[Score]
Mode = BaseGame
DecimalPrecision = 2
DisplayRank = True
CustomRankColors = False
SSColor = #00FFFF
SColor = #FFFFFF
AColor = #00FF00
BColor = #FFFF00
CColor = #FFA700
DColor = #FF0000
EColor = #FF0000
Enabled = True
Position = BelowCombo
Distance = 0

[Personal Best]
DecimalPrecision = 2
TextSize = 2
UnderScore = True
HideFirstScore = True
Enabled = True
Position = BelowCombo
Distance = 1

[Speed]
DecimalPrecision = 2
Mode = Average
Enabled = True
Position = BelowMultiplier
Distance = 1

[Cut]
SeparateSaberCounts = True
Enabled = True
Position = AboveMultiplier
Distance = 0

[Notes Left]
LabelAboveCount = True
Enabled = True
Position = AboveHighway
Distance = 1

[Main]
Enabled = True
AdvancedCounterInfo = True
HideCombo = False
HideMultiplier = True
ComboOffset = 0.2
MultiplierOffset = 0.2

[HUD Settings]
AttachBaseGameHUD = True
AttachToBaseGameHUDFor360 = True
HUDSize = 10
HUDPositionScaleFactor = 10
HUDPosition_X = 0
HUDPosition_Y = 0
HUDPosition_Z = 7
HUDRotation_X = 0
HUDRotation_Y = 0
HUDRotation_Z = 0
AttachHUDToCamera = False
AttachedCamera = MirrorCam5726

[Spinometer]
Mode = Highest
Enabled = False
Position = AboveMultiplier
Distance = 0

Log:
[2020.02.16.19.44.45.log.gz](https://github.com/Caeden117/CountersPlus/files/4211352/2020.02.16.19.44.45.log.gz)

**Probable Culprit**
With the mod updated the only thing i can think of is its just not activating correctly. Maybe some small incompatibility with the new BeatSaber Update.

video too big to upload, contact if needed:

Jona.kats@gmail.com

**Comment by Caeden117** [comment]
This issue has already been addressed in #39, and is fixed for Counters+ 1.8.2.

If you want a build with this feature fixed, [take this buld.](https://github.com/Caeden117/CountersPlus/files/4211523/Counters%2B.zip)
