### ISSUE TITLE
Counters only show up once after game start

### ISSUE THREAD

**Issue by bdkuhman** [Caeden117/CountersPlus#44]
Counters show up for first game, Are gone after playing a second song. Restart fixes, but only for first song.
Using Latest Counters+ 1.8.3 on BS 1.8.0
Beat Saber --verbose Latest:
[_latest.log](https://github.com/Caeden117/CountersPlus/files/4399841/_latest.log)

Counters+ Latest:
[_latest.log](https://github.com/Caeden117/CountersPlus/files/4399843/_latest.log)

**Comment by Caeden117** [comment]
Already fixed for Counters+ 1.8.4 (will be released in like a minute)
