### ISSUE TITLE
Counters+ Bobbing up and down

### ISSUE THREAD

**Issue by joshuasuperboy** [Caeden117/CountersPlus#45]
**Describe the Bug**
The counters+ is bobbing up and down a little later into a song on the newest version of beat saber. It bobs up and down higher and higher and lower and lower.

A GIF showing what was happening.
![2020-04-01 02-19-07](https://user-images.githubusercontent.com/32559193/78110129-1915de00-73c0-11ea-84fd-21877323e706.gif)

A helpful start will be to attach your current Counters+ Config (Located in `Beat Saber/UserData/CountersPlus.ini`) to this report.
[CountersPlus.zip](https://github.com/Caeden117/CountersPlus/files/4413401/CountersPlus.zip)

There is no console errors as i can see.

BeatSaber Counters Plus Logs: [_latest.log](https://github.com/Caeden117/CountersPlus/files/4413411/_latest.log

**Comment by Master1X** [comment]
lulz read settings left side

**Comment by lillebart** [comment]
just got motion sick as fuck, spent 30 min wasting my time to turn it off.... thank you for wasting my time you aholes.

**Comment by Master1X** [comment]
is it so hard to turn off counters+ ? delete a file? wtf

**Comment by ohlookitsderpy** [comment]
@Master1X It's a useful mod? The April fools joke would be better if there was an off button..

**Comment by Master1X** [comment]
maybe there is ?

**Comment by lillebart** [comment]
Yeah, an off button right under "April fool!" would have kept it fun, instead it's a fuck you.

**Comment by lillebart** [comment]
well i just found another bug that made it worse... you have to click off and then back on to the "Main settings" for it to populate the right side panel.

**Comment by lillebart** [comment]
Just discovered that turning off the "April fool tomfoolery" setting does not save, so i can't turn it off even when i found the button... fun!...

**Comment by Master1X** [comment]
lol is there a button ? i did not check for it :D:D:D its fun cmon maybe the joke isn't over

**Comment by siilky** [comment]
just wanted to tell that mod dev should fry on the hell pan until his jokes become at least minimally funny.

**Comment by raftario** [comment]
You not liking the joke doesn't make it bad 🙂

**Comment by Caeden117** [comment]
![looks like modders cant have fun anymore](https://cdn.discordapp.com/attachments/232706807284498432/694955588391534683/giphy2.gif)

[Here's OP's config with April Fools disabled and a build that should fix the menu being fucked up (god i cant have any fun without something going wrong)](https://github.com/Caeden117/CountersPlus/files/4416652/Counters%2B.zip)

**Comment by siilky** [comment]
> You not liking the joke doesn't make it bad 🙂

it's not bad, it's annoying, frustrating and dull, maybe it's good but not funny

**Comment by Master1X** [comment]
all of you mad bois have no sense of humor
for real the first moment i was like wtf is this. next song again then wtf is it.... config or bug or or or. then looked into settings and lold

**Comment by ohlookitsderpy** [comment]
> all of you mad bois have no sense of humor
Yeah imagine not wanting to get motion sickness

>Here's OP's config with April Fools disabled and a build that should fix the menu being fucked up (god i cant have any fun without something going wrong)
Not sure if it's just me, but my config didn't have anything related to April Fools in it?

**Comment by Caeden117** [comment]
Counters+ rolls back to defaults if it doesn't exist in config.

If you absolutely positively do not want a bouncy castle of a HUD, add this to the bottom of your `CountersPlus.ini` file

```
[Main]
AprilFoolsTomfoolery = False
```

If there's a Main section that already exists, just add the April Fools setting there.

**Comment by ohlookitsderpy** [comment]
I think this issue has been resolved, can we close it please?

**Comment by Caeden117** [comment]
I think I'm going to leave this issue open until tomorrow for any other people who'd like to flame me for making a bouncy castle out of their Counters+ HUD.

**Comment by flotos** [comment]
The settings are not saved after I leave its settings so I cant disable it without removing the mod

**Comment by Caeden117** [comment]
[Hi, please follow these instructions.](https://github.com/Caeden117/CountersPlus/issues/45#issuecomment-607415037)

**Comment by Master1X** [comment]
> 
> 
> I think I'm going to leave this issue open until tomorrow for any other people who'd like to flame me for making a bouncy castle out of their Counters+ HUD.

i love you

**Comment by Tsonux** [comment]
So uh, I like this. Any chance of making this a configurable thing, as in enable/disable anytime and maybe a limiter on how far up and down it'll go? Long shot maybe, but I figured I'd shoot it out there.

**Comment by joshuasuperboy** [comment]
Ok so im closing this as it was an april fools thing and too many people are hating on this.
