### ISSUE TITLE
Right panel in settings menu problems

### ISSUE THREAD

**Issue by lillebart** [Caeden117/CountersPlus#46]
When you first enter the settings menu after launching the game, there is a massage about how to use the settings menu. Everything works fine first time you enter the menu, but if you went into the menu and change something (i changed progress time left to enable) and then went out to the main menu and back, problems starts popping up. The right side panel is populated with the last menu you had open before exiting before and if you go into the main settings menu and change "April Fools tomfoolery" the setting wont save. 

hope this helps, but April fools jokes are bad when users have problems turning it off.

**Comment by Caeden117** [comment]
[Try this build and tell me how things go.](https://github.com/Caeden117/CountersPlus/files/4416620/Counters%2B.zip)

**Comment by lillebart** [comment]
It didn't fix the save issue, but the menu seems to update properly now.
I found if you open the mods settings the first time it always works and save what i set, but after that 9 out of 10 times if i go in and change any setting(s) in the mods general settings menu the changes wont save, and if i go back into the mods settings menu (click on donate then back on general settings for the panel to update) and the settings have reverted.

**Comment by Caeden117** [comment]
[Take two, I think this should be the one.](https://github.com/Caeden117/CountersPlus/files/4417375/Counters%2B.zip)

**Comment by lillebart** [comment]
Didn't fix it either, but i now noticed that if i reopen the settings menu and the general settings menu is already loaded on the right panel, the settings save, otherwise they don't.
