### ISSUE TITLE
Enabling Counters+ causes energy bar to be affected by debris distortion effects

### ISSUE THREAD

**Issue by chenxiaolong** [Caeden117/CountersPlus#51]
**Describe the Bug**

When reduced debris is enabled and Settings -> Advanced Graphics -> Screen Distortion Effects is also enabled, Counters+ seems to cause the energy bar to be affected by the distortion effects. The whole energy bar will "vibrate"/displace with every note slice. This is visible in both the Camera+ rendering and the HMD. If Counters+ is disabled via the menu option, then the energy bar behaves normally and stays in place.

I've tested this with a clean installation and only the following mods installed:
* BSIPA 4.0.5
* CameraPlus 4.1.2
* Counters+ 1.8.4
* (SongCore + its dependencies)

**Attach or Link Files**

Counters+ log file from the run exhibiting the issue (bottom left quadrant of the video below): https://gist.github.com/chenxiaolong/940b0e26a8401d6f531cd64490965c57

The default generated `CountersPlus.ini` configs were used: https://gist.github.com/chenxiaolong/ee90b501dda57ffaee329174c4a04879

**Probable Culprit**

I've briefly looked over the code and I haven't had any luck finding what might be causing this. It seems that Counters+ doesn't use the energy bar for anything except positioning a counter.

**Screenshots or Video**

Video: https://youtu.be/r3miYbZJG4M (original 4K `.mp4` in case YouTube's compression makes it hard to see: https://noobdev.io/BeatSaber/20200513_Counters+_Distortion_Bug.mp4)

The top two quadrants show the base game behavior with no mods. The energy bar always remains in place regardless of which effects are enabled or which debris mode is used.

The bottom left quadrant shows the problematic behavior when Counters+ is installed. The energy bar will move with each slice of a note. The bottom right quadrant shows that this problem doesn't occur if distortion effects are disabled while Counters+ is enabled.

**Additional context**

I've also tried building the latest code from the master branch (commit 12e1ca53c88cb7fea9edb9643f367cd0ed580959 at the time of writing) and the behavior is still the same. If there's any other information that's needed, I'd be happy to provide it.

**Comment by chenxiaolong** [comment]
Actually, now that I look at the video more closely, it seems that the Counters+ counters are being affected by the distortion effects too. Maybe this is somehow impacting the entire HUD?

**Comment by Caeden117** [comment]
If I had to guess, the shockwave effect is ignoring a certain layer ID that the base game HUD is assigned to, but that Counters+'s HUD isn't.

I'll try copying over the layer ID from the base game HUD.

**Comment by chenxiaolong** [comment]
Wow, thanks for the quick reply! I'd be happy to compile and test the change when ready.

**Comment by Caeden117** [comment]
[Try this build.](https://github.com/Caeden117/CountersPlus/files/4625871/Counters%2B.zip)

**Comment by chenxiaolong** [comment]
Unfortunately, that didn't do the trick. Logs: 
[2020.05.13.23.22.58.log](https://github.com/Caeden117/CountersPlus/files/4625883/2020.05.13.23.22.58.log)

**Comment by Caeden117** [comment]
[I do believe this is fixed, if you can confirm for me that'll be great](https://github.com/Caeden117/CountersPlus/files/4625985/Counters%2B.zip)

**Comment by chenxiaolong** [comment]
Confirmed; it's working great. Thank you!
