### ISSUE TITLE
Accuracy/rank counter positioning bug.

### ISSUE THREAD

**Issue by Rayn322** [Caeden117/CountersPlus#53]
**Describe the Bug**
The accuracy and rank counter shows up in the middle of the lanes rather than on the side, below the combo.

**Attach or Link Files**

[CountersPlusIni.zip](https://github.com/Caeden117/CountersPlus/files/4678997/CountersPlusIni.zip)

A helpful start will be to attach your current Counters+ Config (Located in `Beat Saber/UserData/CountersPlus.ini`) to this report.

If you wish to be even more helpful, try taking a screenshot of the Beat Saber Console when you reproduce the issue (`--verbose` in the start arguments. You can use Google to figure out how to take a screenshot.)

If you want to be my best friend, attach the latest log with a date and time name (**Not** `latest.log.gz`), located in `Beat Saber/Logs/Counters+`.

**Probable Culprit**
uhhhh

**Screenshots or Video**
![Desktop Screenshot 2020 05 25 - 15 31 17 38](https://user-images.githubusercontent.com/16494880/82846324-148c1400-9e9d-11ea-9a5c-cb8ee7c055a9.png)

**Additional context**

**Comment by Caeden117** [comment]
Hmm, strange.

I'm a bit busy right now, but ill get to this when I can.

**Comment by Rayn322** [comment]
Thanks! Let me know if you need me to send logs or something.

**Comment by nikom202** [comment]
[CountersPlusIni (2).zip](https://github.com/Caeden117/CountersPlus/files/4697077/CountersPlusIni.2.zip)


am I doing this right

**Comment by Rayn322** [comment]
Oh you have the same problem too?

**Comment by nikom202** [comment]
Yes I do :/

**Comment by Caeden117** [comment]
Fixed in Counters+ 1.9.1
