### ISSUE TITLE
Accuracy counter being slightly off

### ISSUE THREAD

**Issue by ErisApps** [Caeden117/CountersPlus#55]
**Describe the Bug**
At the end of a song, the accuracy counter seems to be slightly off (often ~0.1% diff) compared to the actual percentage of the Personal Best counter and ScoreSaber leaderboards percentage afterwards. 

**Attach or Link Files**
Counters+ config (extension renamed to txt because of github)
[CountersPlus.txt](https://github.com/Caeden117/CountersPlus/files/4776960/CountersPlus.txt)

Log gzip file related to the video below.
[2020.06.07.16.25.10.log.gz](https://github.com/Caeden117/CountersPlus/files/4776971/2020.06.07.16.25.10.log.gz)

**Probable Culprit**
I've been looking in the code, but I honestly don't have a clue right now.
My mods were up-to-date afaik at the time of the log.

**Screenshots or Video**
In the following clip, the song is about to end. Pay attention to the ingame accuracy and personal best counters (both on the right side) 
https://www.twitch.tv/videos/643954117?t=00h17m15s

**Additional context**
All the mods being used at that moment can also be found in the log zip 😄

If there's any need for me to reproduce things or provide other stuff, please give me a mention on Discord as well 🙂

**Comment by Caeden117** [comment]
Already fixed in commit 949eb071d7ef378a3241d4abe8dbf3df380523df
