### ISSUE TITLE
Counters not visible through walls

### ISSUE THREAD

**Issue by ErisApps** [Caeden117/CountersPlus#56]
**Describe the Bug**
Just like the title states, all counters aren't visible when observed through a wall.

**Attach or Link Files**
Counters+ config file
[CountersPlus.txt](https://github.com/Caeden117/CountersPlus/files/4777023/CountersPlus.txt)

Logs before the issue
[2020.05.19.20.37.47.log.gz](https://github.com/Caeden117/CountersPlus/files/4777018/2020.05.19.20.37.47.log.gz)

Logs after the issue appeared
[2020.05.28.13.15.49.log.gz](https://github.com/Caeden117/CountersPlus/files/4777019/2020.05.28.13.15.49.log.gz)

**Probable Culprit**
The main changes I saw in the log zips myself were an update of BS itself (1.9.1 -> 1.10.0) and an update of Counters+ (1.8.4 -> 1.9.0)
Also, after some back and forth messaging, you mentioned that issue #51 might be related to this.

**Screenshots or Video**
Video which contains the bug
https://www.youtube.com/watch?v=ibWMytu_HL8

**Additional context**
I think that everything that I can add has been added already, if you need something else, please let me know 🙂

**Comment by kinsi55** [comment]
https://github.com/Caeden117/CountersPlus/blob/2a79c6e178fb904309f4d2c70cd37c466f24c736/Counters%2B/Utils/CanvasUtility.cs#L135

Disable the ignore shockwave effect and boom, you see counters through walls.
