### ISSUE TITLE
Current % amount ain't accurate to what is actually achieved in game.

### ISSUE THREAD

**Issue by Rockster34** [Caeden117/CountersPlus#57]
**Describe the Bug**
Counters+ is not accurate with current amount of % (Also if you haven't cleared a song before your "previous" score is far more accurate then the current amount)

**Attach or Link Files**
Config (https://pastebin.com/hnA4N4rT)

**Probable Culprit**
The cause of this is genuinely unknown to me because it used to work just fine and be accurate to the decimal.

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/13683726/85952216-15b2d400-b968-11ea-9ef4-185e9cb851a9.png)
(I didn't improve my score afterward I swear it's just a really odd bug)
Talking about this counter to make it clear.
![image](https://user-images.githubusercontent.com/13683726/85952307-9ffb3800-b968-11ea-8a83-ab5d28f5f1db.png)

**Additional context**

**Comment by Caeden117** [comment]
Fixed in Counters+ 1.9.1
