### ISSUE TITLE
Mod does not appear in ModManager (outdated GameVersion target in manifest.json?)

### ISSUE THREAD

**Issue by Amunak** [Caeden117/CountersPlus#59]
**Describe the Bug**
After the latest update Counters+ doesn't show up in ModAssistant, despite that being the proclaimed installation method.

**Probable Culprit**
I don't mod for Beat Saber but I assume you have to declare compatibility with each new game version. The file [manifest.json declares version 1.9.0](https://github.com/Caeden117/CountersPlus/blob/master/Counters%2B/manifest.json#L5), when the latest is 1.11.1.

I have downloaded the mod manually and verified that it works seemingly without issue, so it's probably really just about the version bump.

It's a shame; I played for a while without it and felt completely lost with the vanilla game UI! I assume a lot of people use ModAssistant to install the mod and are just as unhappy to see it gone.

**Comment by Caeden117** [comment]
Hi,

Counters+ has been going through a complete internal rewrite, which is [viewable in the rewrite branch](https://github.com/Caeden117/CountersPlus/tree/rewrite). The 2.0.0 update is almost complete, but needs certain dependencies to also be uploaded to BeatMods. You can [obtain a Release Candidate version of Counters+ here](https://github.com/Caeden117/CountersPlus/releases/tag/2.0.0-rc1).
