### ISSUE TITLE
CountersPlus.ini gets overwritten with defaults on game start

### ISSUE THREAD

**Issue by xhuytox** [Caeden117/CountersPlus#6]
How to reproduce:
1) Make changes in CounterPlus settings in game
2) Quit game
3) Check CountersPlus.ini matches what was set in game
4) Open game
5) Check that CountersPlus.ini is now overwritten with defaults

This does not just apply to the first time the game is started after CountersPlus is updated but every time the user quits and starts the game again.

**Comment by Caeden117** [comment]
Alright it appears to be how I am detecting a valid config file. I've linked a test build over to the other issue.
