### ISSUE TITLE
Add option to count bad cuts as missed

### ISSUE THREAD

**Issue by Sneakometer** [Caeden117/CountersPlus#60]
I would really like to have bad cuts show up in the miss counter. I know, the base game does not do this in the level finished screen, but every elsewhere in the community a bad cut is considered as a normal miss. I came across this when watching videos from the Cube Community youtube channel where people got consufed in the comments because the miss counter didn't go up but the multiplier went down from 8x to 1x.

Maybe it would be nice to have an option for this called "count bad cuts" in the counters+ miss config menu?

Thank you.

**Comment by Caeden117** [comment]
A "Count Bad Cuts" option has already been added into Counters+ 2.0, which is currently waiting approval for ModAssistant.
