### ISSUE TITLE
Multiplier ring effect not hidden

### ISSUE THREAD

**Issue by Kakifrucht** [Caeden117/CountersPlus#61]
When setting the multiplier hidden, the effect when you reach a higher multiplier will still show. This is on the latest release you just pushed.

See right side:
![ringbug](https://i.imgur.com/pLKFoqU.png)

**Comment by Caeden117** [comment]
Alright, this has been fixed.

Due to the swiftness of this bug's reporting and solution, I've went ahead and directly replaced the build provided in the Counters+ 2.0.0 release, you can just redownload and it should fix itself.

**Comment by Kakifrucht** [comment]
Awesome, thanks for your continued support!
