### ISSUE TITLE
[2.0.0.0] Rank not displayed in score counter

### ISSUE THREAD

**Issue by Protected** [Caeden117/CountersPlus#64]
**Describe the Bug**
I have the 2.0.0.0 release according to the file version of the .dll itself (installed recently). Everything's working fine, except the rank for the current song doesn't seem to be displayed in the score panel. It has never been displayed, even in the v2 development builds. I thought it was one of the issues you were fixing after the RC.

**Attach or Link Files**
Config file: https://gist.github.com/Protected/3e483d38814655044cd2b4c715a1827c
Log: https://gist.github.com/Protected/eb89d79536e3e666384ed6f22ef0a5ec

**Probable Culprit**
Sorry, no idea. 

**Screenshots or Video**
Both of these are using the 2.0.0.0 release:
https://www.twitch.tv/videos/751094154
https://www.twitch.tv/videos/754917310
(Will expire in a week or so)
I expected the rank to appear on the right hand side below the score, as it used to in previous versions.

**Additional context**
Installed mods: https://gist.github.com/Protected/94b80f729e3b391adae23a09f5762dc1

**Comment by Caeden117** [comment]
Looks (and sounds to me) like you do not have the `Advanced HUD` option enabled, located in the base game's `Player Settings`.

**Comment by Protected** [comment]
Correct. No idea that was there. Enabling it fixed the problem. What else does that do?

**Comment by Caeden117** [comment]
Not only does it bring advanced score counter options (Percentage and current rank), but it also would bring up the progress counter (if it was not already being replaced by Counters+'s own version)
