### ISSUE TITLE
Score counter is scuffed

### ISSUE THREAD

**Issue by The-Demp** [Caeden117/CountersPlus#65]
**Describe the Bug**
There are 2 issues here: 

1. Without the personal best counter, the score counter places itself significantly lower than it should be.
2. Rank does not display regardless of placement.

**Attach or Link Files**

Config file: [CountersPlus.json](https://github.com/Caeden117/CountersPlus/files/5321208/CountersPlus.txt)

Log: [2020.10.02.16.18.49.log](https://github.com/Caeden117/CountersPlus/files/5321209/2020.10.02.16.18.49.log)

**Probable Culprit**
It's probably something specific to score counter. Dependencies are all latest (SiraUtil 1.0.2 and BSML 1.3.5 from Mod Assistant, BSIPA 4.1.0 from GitHub). Of note, minor version of Mod Assistant dependencies is higher than the release page asks for, but I would hope/assume this isn't the issue.

**Screenshots or Video**
Taken in FPFC, but issue occurs in normal game as well. Score counter is below multiplier ![image](https://user-images.githubusercontent.com/10623820/94984924-57728e00-0506-11eb-89de-4408ba22b06f.png)

**Additional context**
Been seeing this issue since 2.0.0 release. Didn't have the problem in the RC. Adding the personal best counter puts the score counter in the right place but the rank still doesn't show.

**Bonus bug**
The miss counter is not visible through the floor in Linkin Park. Honestly it doesn't bother me enough to reproduce and file another issue but if you know an easy fix have at it.

**Comment by OoDeeR** [comment]
I can confirm that something is scuffed with the score counter. It completely disappeared in my case. Will update with log file soon.

**Comment by Caeden117** [comment]
Hi all,

sorry for the long response, I'll look into this while fixing Counters+ for the next beat saber version.

**Comment by Caeden117** [comment]
This issue has been fixed as of Counters+ 2.1.0, a beta of which is available on GitHub.
