### ISSUE TITLE
Gig Grey-ish Square showing up when Clicking

### ISSUE THREAD

**Issue by cadavren** [Caeden117/CountersPlus#68]
Hello Hello !
I have noticed that whevener I clicked something after I have been in Counter+ menu (no matter if I din't change something or not, I just need to enter and get out of it) I have a grey square showing up (seems like a animation but there is no transparency nor the teture it is supposed to show). the square is animated and shows up on whatever I click, main menu, maps, options, other mods, party, multiplayer menus, etc. If I don't enter the menu after rebooting the game, it doesn't do this ! so it is okey as long as you don't wanna change something.

here is my lastest log for counter+
[_latest.log](https://github.com/Caeden117/CountersPlus/files/5429160/_latest.log)
and for the game it self
[_latest.log](https://github.com/Caeden117/CountersPlus/files/5429163/_latest.log)

Tried to take some screen cap to show what it looks like
![20201023132051_1](https://user-images.githubusercontent.com/61839268/96997981-0ec15a00-1533-11eb-9ba0-f10ecaa36eaf.jpg)
![20201023132102_1](https://user-images.githubusercontent.com/61839268/96997983-0ff28700-1533-11eb-94ea-4a4639f63ff1.jpg)
![20201023132112_1](https://user-images.githubusercontent.com/61839268/96997984-108b1d80-1533-11eb-8843-a1368be29bc9.jpg)
![20201023132132_1](https://user-images.githubusercontent.com/61839268/96997990-1123b400-1533-11eb-99c5-bf5e56649a92.jpg)
![20201023132038_1](https://user-images.githubusercontent.com/61839268/96997993-11bc4a80-1533-11eb-9d72-6de49696e03d.jpg)
![20201023132040_1](https://user-images.githubusercontent.com/61839268/96997998-1254e100-1533-11eb-941d-da12f7158d82.jpg)
![20201023132043_1](https://user-images.githubusercontent.com/61839268/96998002-12ed7780-1533-11eb-9785-a4fdadf07c52.jpg)
![20201023132048_1](https://user-images.githubusercontent.com/61839268/96998006-13860e00-1533-11eb-97cf-d5c81657b216.jpg)

If anything we tried to do this without other mods, it was still doing it.

**Comment by oksoff** [comment]
Can confirm
https://streamable.com/kfnkq5
[_latest.log](https://github.com/Caeden117/CountersPlus/files/5431793/_latest.log)

**Comment by RafaelSchridi** [comment]
Also seeing the same thing here, requires a restart to fix.

**Comment by Caeden117** [comment]
Alright, thanks for the input everyone, I'll look into this when I get the chance

**Comment by boulders2000** [comment]
I never have this issue.... I can go in and out just fine without that ever happening

**Comment by Caeden117** [comment]
Fixed in Counters+ `2.1.1`.
