### ISSUE TITLE
Live rank (e.g. A, S, SS) and percentage won't appear under score

### ISSUE THREAD

**Issue by zoetropik** [Caeden117/CountersPlus#70]
Hi! Thanks as always for updating Counters+ to work with the latest Beat Saber client.

Sadly, I'm encountering an issue where both the live rank (e.g. A, S, SS) and the percentage of the current max score it's calculated from refuse to display beneath the score. I've tried enabling and disabling the relevant toggle switch under settings, changing the colours of the various rank tiers, restarting the game, etc., but there's only ever a huge blank space between the score and the "Personal Best" percentage at the bottom on the right side.

For my style of play, a live rank display is even more crucial than the actual score, as if I see I'm slacking off at the lower end of the SS tier, I can pull up my socks and work to get back up to around 93-94%. Without it, I have no idea how well I've done until the end screen pops up. So if you can think of anything that would be causing Rank to refuse to display, please let me know. You'd be my hero! ;-)

**Comment by PaperT1D** [comment]
Turn on Advanced HUD in player settings (it's a base game option).

**Comment by zoetropik** [comment]
Thanks! I'll give that a go the next time I reboot into Windows (probably tomorrow morning, just before my daily Beat Saber sesh). I'll report back whether that cures the missing Rank display under Counters+. ;-)

**Comment by mondychan** [comment]
thanks a bunch! i couldnt figure why it isnt working for me! turning on advanced hud "fixed" it *thumbs up*

**Comment by zoetropik** [comment]
Oops! I forgot to come back and thank you for the solution, @PaperT1D... it worked for me too! ;-)

**Comment by Caeden117** [comment]
alright, looks like everyone's solved this problem!
