### ISSUE TITLE
1.13 something wrong

### ISSUE THREAD

**Issue by 171753355** [Caeden117/CountersPlus#71]
The right window only displays the total score, not the percentage and grade, 95% and SS are not displayed

**Comment by PaperT1D** [comment]
https://github.com/Caeden117/CountersPlus/issues/70#issuecomment-728629354

**Comment by Caeden117** [comment]
This is a duplicate of #70 

To enable the Percentage and Letter Rank, turn on `Advanced HUD` found in the base game Player Settings.
