### ISSUE TITLE
Score Counter doesn't show Rank and Percentage when Advanced HUD is disabled

### ISSUE THREAD

**Issue by Philip6294** [Caeden117/CountersPlus#74]
**Describe the Bug**
The Score Counter doesn't show the Rank and Percentage when Advanced HUD in Player Settings is disabled 

**Attach or Link Files**
[_latest.log](https://github.com/Caeden117/CountersPlus/files/5617031/_latest.log)
[CountersPlus.json.txt](https://github.com/Caeden117/CountersPlus/files/5617036/CountersPlus.json.txt)

**Screenshots or Video**
Advanced HUD enabled ![grafik](https://user-images.githubusercontent.com/18615404/100633080-e7c62700-332d-11eb-92e5-0dd5f039599d.png)
Advanced HUD disabled ![grafik](https://user-images.githubusercontent.com/18615404/100633161-02989b80-332e-11eb-8372-25745160089f.png)

**Comment by Caeden117** [comment]
Uhhh... yes. This is perfectly intended behavior by the base game, and I currently have no plans to correct it, or "override" it with a Counters+ option.
