### ISSUE TITLE
I can't find my Counters+ mod in the Mods tab to the left.

### ISSUE THREAD

**Issue by ycuglu** [Caeden117/CountersPlus#75]
When I launch Beat Saber, Counters+ doesn't show in my mods tab, all other mods work, but not Counters+.

Here are my logs:

My whole Beat Saber log:
[_latest.log](https://github.com/Caeden117/CountersPlus/files/5649083/_latest.log)

Counters+ Log:
[_latest.log](https://github.com/Caeden117/CountersPlus/files/5649086/_latest.log)

**Comment by Caeden117** [comment]
Hi, please check that you have a `CountersPlus.dll` in the `Plugins` folder of your beat saber install

**Comment by ycuglu** [comment]
Hello again, thank you as the problem was that the name of the .dll was wrong, and you told me what to rename it to, although that wasn't what you said, it still helped me. Thanks!
