### ISSUE TITLE
Black screen after clicking "Continue" on Health and Safety Warning in 1.13.5

### ISSUE THREAD

**Issue by JTandT** [Caeden117/CountersPlus#83]
**Describe the Bug**
When launching Beat Saber 1.13.5 with Counters+ installed, the game only displays a black screen after clicking "Continue" on the Health and Safety Warning. The menu music plays but the monitor and headset only display a black screen.

**Attach or Link Files**
[_latest.log](https://github.com/Caeden117/CountersPlus/files/6139316/_latest.log)
[CountersPlus.json.txt](https://github.com/Caeden117/CountersPlus/files/6139318/CountersPlus.json.txt)

**Additional context**
After uninstalling Counters+ my game works fine, so either Counters+ is broken in 1.13.5 or it's conflicting with another mod. My complete mod list can be found in the latest.log file.

**Comment by Caeden117** [comment]
Counters+ is not yet updated for Beat Saber 1.13.4 and 1.13.5. Please be patient!
