### ISSUE TITLE
I have crippling cyberbully problem!

### ISSUE THREAD

**Issue by Heavenira** [Caeden117/CountersPlus#90]
**Is it because of an issue?**
Yes it is! I am being cyberbullied!

**Describe your solution**
Cyberbully them back. Don't let them take control of you.

**A programmer yourself?**
what is vr

**Comment by Heavenira** [comment]
OH I didn't mean to make a thread, I was told by Jack to respond to a preexisting thread

**Comment by Caeden117** [comment]
damn that sucks

hope you get better soon

**Comment by Heavenira** [comment]
Hooray! The issue is now closed! I no longer get cyberbullied. Thank you for your continued support!
