### ISSUE TITLE
Readme Installation Section Wording

### ISSUE THREAD

**Issue by Coy-Allen** [Caeden117/CountersPlus#92]
The installation section of the README.md seems to mention ModAssistant as a way to install Counters+ but it is not listed in the program's mod list.
However, I might be reading this wrong or I just missed it in the mod list.
> To install Counters+, simply use a Beat Saber mod manager such as ModAssistant. This will ensure that any dependencies are installed along with Counters+.

**Comment by Caeden117** [comment]
To keep it brief, Counters+ has to go through an approval phase before being brought onto Mod Assistant. This phase includes a manual review of all the code, as well as thorough tests to make sure that every part of the mod works as intended. This is entirely volunteer driven, and unfortunately we only have like one person who is motivated enough to actually go through the queue.

Counters+ has been in approval hell for the past few months. Currently, the only way to get Counters+ is through the [releases page](https://github.com/Caeden117/CountersPlus/releases). To be honest, I expect Counters+ to stay in approval hell until we throw it out and completely reform how mods are uploaded and approved for public use.

Sorry about that.
